sudo: false
language: python
os:
  - linux
  #- osx  # unsupported yet
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy3.5"
env:
  - PILLOW_VERSION=5.0.0
  - PILLOW_VERSION=6.0.0
install:
  - pip install pillow==$PILLOW_VERSION pytest
  - python setup.py install
script: pytest
